### ISSUE TITLE
User: events issues

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc15/mmlab#111]
- change label to "events co-organized"
- List of titles, no teasers
- Try to put the publications underneath and collapsible instead of the tab (if possible, because this is generated by the biblio module)

**Comment by dieterbeelaert** [comment]
Label changed + list of titles no teasers

**Comment by dieterbeelaert** [comment]
@Izoman you're the biblio expert in our team can you take a look at the last issue in this list?

**Comment by Izoman** [comment]
Biblio gives only 3 options for publications:
- Show in a tab
- Show in navigation menu
- Hide

So to fix this, a view with contextual filter on user id is required

**Comment by Izoman** [comment]
To hide publications go to Configuration > Biblio settings > Profile page:
![forhiding](https://cloud.githubusercontent.com/assets/13185885/9406654/cebb33d4-4802-11e5-82d0-38108347564a.PNG)

**Comment by dieterbeelaert** [comment]
view created and configured + needs some aditional css (commit is coming soon ;-) )
