### ISSUE TITLE
Fix tabs styling

### ISSUE THREAD

**Issue by mietcls** [oSoc15/mmlab#50]
![schermafbeelding 2015-07-30 om 23 39 09](https://cloud.githubusercontent.com/assets/1572885/8995820/35006f60-3714-11e5-8332-c6f4b4676e61.png)

Make them look like tabs again, they look like buttons now but behave like tabs. You can style these like the sort buttons.

**Comment by mietcls** [comment]
![schermafbeelding 2015-07-31 om 00 26 08](https://cloud.githubusercontent.com/assets/1572885/8996749/cfe89cf4-371a-11e5-9197-f21a0f2a0829.png)

**Comment by elroyK** [comment]
Added hover attributes
