### ISSUE TITLE
Create cards for information fields in publication detail pages and project detail pages

### ISSUE THREAD

**Issue by mietcls** [oSoc15/mmlab#62]
These blocks are quite alike on both pages. Figure out a way to put these into a card-like design to the right of the page.

![schermafbeelding 2015-07-31 om 01 23 07](https://cloud.githubusercontent.com/assets/1572885/8997571/115af7ba-3723-11e5-838f-71004494ae15.png)
![schermafbeelding 2015-07-31 om 01 22 43](https://cloud.githubusercontent.com/assets/1572885/8997572/115b165a-3723-11e5-9af2-85bcbc444ce7.png)

**Comment by elroyK** [comment]
Need backend to group all the text-fields in a div.
