### ISSUE TITLE
Spotlight menu - Adding items

### ISSUE THREAD

**Issue by elroyK** [oSoc15/mmlab#85]
Find a way to add links to the Spotlight menu from the contents' pages and not from the menu page

**Comment by dieterbeelaert** [comment]
Should be awesome if we could display a "random" list of spotlighted items so we're not limited of those few spotlight items

**Comment by dieterbeelaert** [comment]
I have taken a look to it, and the provided drupal functionality will do to edit that menu, same for item limit
