### ISSUE TITLE
Spotlight menu - Fixing an item limit

### ISSUE THREAD

**Issue by elroyK** [oSoc15/mmlab#86]
The Spotlight shouldn't expand too much so a limiting option has to be added.
First solution found : 

```
.home__spotlight .leaf{
   display: none;
   }

.home__spotlight .leaf:first-child, .home__spotlight .leaf:nth-child(2), .home__spotlight .leaf:nth-child(3), .home__spotlight .leaf:nth-child(4){
    display: list-item;}
```

This would limit the number of displayed item to 4, but we can have it be higher or lower depending on needs (see with Frank)

**Comment by dieterbeelaert** [comment]
I commented something about a random list see my comment on issue #85

**Comment by dieterbeelaert** [comment]
I wouldn't add a limit to that, and leave the responsibility to the site maintainers. If we would add an item limit we also "lose" data if they want to add more items so let's just leave it as it is
